# Generated by go2rpm 1.8.1
%bcond_without check
%global debug_package %{nil}

# https://github.com/mattn/go-localereader
%global goipath         github.com/mattn/go-localereader
Version:                0.0.1

%gometa -f

%global common_description %{expand:
CodePage decoder for Windows.}

%global godocs          README.md

Name:           %{goname}
Release:        %autorelease
Summary:        CodePage decoder for Windows

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
# TestDecoder should be tested only on Windows
for test in "TestDecoder"\
; do
awk -i inplace '/^func.*'"$test"'\(/ { print; print "\tt.Skip(\"disabled failing test\")"; next}1' $(grep -rl $test)
done
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
