# Generated by go2rpm 1.8.1
%bcond_without check
%global debug_package %{nil}

# https://github.com/digitalocean/godo
%global goipath         github.com/digitalocean/godo
Version:                1.93.0

%gometa

%global common_description %{expand:
DigitalOcean Go API client.}

%global golicenses      LICENSE.txt
%global godocs          CHANGELOG.md CONTRIBUTING.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        DigitalOcean Go API client

License:        MIT and BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
