# Generated by go2rpm 1.8.1
# https://github.com/erikgeiser/promptkit/issues/15
# All tests fail with newer termenv release as there are some style changes
%bcond_with check
%global debug_package %{nil}

# https://github.com/erikgeiser/promptkit
%global goipath         github.com/erikgeiser/promptkit
Version:                0.7.0
%global commit          1f33bc73d091f90faf118ee5ab5d85cb6474ca7c

%gometa -f

%global common_description %{expand:
Go prompt library.}

%global golicenses      LICENSE
%global godocs          examples README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go prompt library

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
